language: node_js
node_js:
  - "12.6"
cache:
  directories:
  - node_modules
install:
  - yarn install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master

